# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/edit_servers_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget.verticalHeader().setDefaultSectionSize(27)
        self.tableWidget.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_pushButton = QtWidgets.QPushButton(Dialog)
        self.add_pushButton.setObjectName("add_pushButton")
        self.horizontalLayout.addWidget(self.add_pushButton)
        self.copy_pushButton = QtWidgets.QPushButton(Dialog)
        self.copy_pushButton.setObjectName("copy_pushButton")
        self.horizontalLayout.addWidget(self.copy_pushButton)
        self.del_pushButton = QtWidgets.QPushButton(Dialog)
        self.del_pushButton.setObjectName("del_pushButton")
        self.horizontalLayout.addWidget(self.del_pushButton)
        self.clear_pushButton = QtWidgets.QPushButton(Dialog)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.horizontalLayout.addWidget(self.clear_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.save_pushButton = QtWidgets.QPushButton(Dialog)
        self.save_pushButton.setObjectName("save_pushButton")
        self.horizontalLayout.addWidget(self.save_pushButton)
        self.close_pushButton = QtWidgets.QPushButton(Dialog)
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout.addWidget(self.close_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tableWidget, self.add_pushButton)
        Dialog.setTabOrder(self.add_pushButton, self.copy_pushButton)
        Dialog.setTabOrder(self.copy_pushButton, self.del_pushButton)
        Dialog.setTabOrder(self.del_pushButton, self.clear_pushButton)
        Dialog.setTabOrder(self.clear_pushButton, self.save_pushButton)
        Dialog.setTabOrder(self.save_pushButton, self.close_pushButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "编辑服务器列表"))
        self.tableWidget.setSortingEnabled(False)
        self.add_pushButton.setText(_translate("Dialog", "增加"))
        self.copy_pushButton.setText(_translate("Dialog", "复制"))
        self.del_pushButton.setText(_translate("Dialog", "删除"))
        self.clear_pushButton.setText(_translate("Dialog", "清空"))
        self.save_pushButton.setText(_translate("Dialog", "保存"))
        self.close_pushButton.setText(_translate("Dialog", "关闭"))
