# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/resource_monitor_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(750, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # 第一部分：系统/进程监控内容（左右两列）
        self.top_horizontalLayout = QtWidgets.QHBoxLayout()
        self.top_horizontalLayout.setObjectName("top_horizontalLayout")
        
        # 左列：系统监控
        self.sys_widget = QtWidgets.QWidget()
        self.sys_layout = QtWidgets.QVBoxLayout(self.sys_widget)
        self.sys_label = QtWidgets.QLabel(Dialog)
        self.sys_label.setObjectName("sys_label")
        self.sys_layout.addWidget(self.sys_label)
        self.sys_plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.sys_plainTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sys_plainTextEdit.setLineWidth(0)
        self.sys_plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sys_plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sys_plainTextEdit.setReadOnly(True)
        self.sys_plainTextEdit.setMinimumHeight(100)
        self.sys_plainTextEdit.setMaximumHeight(100)
        self.sys_plainTextEdit.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.sys_plainTextEdit.setObjectName("sys_plainTextEdit")
        self.sys_layout.addWidget(self.sys_plainTextEdit)
        self.top_horizontalLayout.addWidget(self.sys_widget)
        
        # 右列：进程监控
        self.process_widget = QtWidgets.QWidget()
        self.process_layout = QtWidgets.QVBoxLayout(self.process_widget)
        self.process_label = QtWidgets.QLabel(Dialog)
        self.process_label.setObjectName("process_label")
        self.process_layout.addWidget(self.process_label)
        self.process_plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.process_plainTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.process_plainTextEdit.setLineWidth(0)
        self.process_plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.process_plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.process_plainTextEdit.setReadOnly(True)
        self.process_plainTextEdit.setMinimumHeight(100)
        self.process_plainTextEdit.setMaximumHeight(100)
        self.process_plainTextEdit.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.process_plainTextEdit.setObjectName("process_plainTextEdit")
        self.process_layout.addWidget(self.process_plainTextEdit)
        self.top_horizontalLayout.addWidget(self.process_widget)
        
        self.verticalLayout.addLayout(self.top_horizontalLayout)
        
        # 第二部分：进程名称
        self.process_names_horizontalLayout = QtWidgets.QHBoxLayout()
        self.process_names_horizontalLayout.setObjectName("process_names_horizontalLayout")
        self.process_names_label = QtWidgets.QLabel(Dialog)
        self.process_names_label.setObjectName("process_names_label")
        self.process_names_horizontalLayout.addWidget(self.process_names_label)
        self.process_input_plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.process_input_plainTextEdit.setPlainText("")
        self.process_input_plainTextEdit.setObjectName("process_input_plainTextEdit")
        self.process_names_horizontalLayout.addWidget(self.process_input_plainTextEdit)
        self.verticalLayout.addLayout(self.process_names_horizontalLayout)
        
        # 第三部分：采样频率+监控时长（一行）
        self.params_horizontalLayout = QtWidgets.QHBoxLayout()
        self.params_horizontalLayout.setObjectName("params_horizontalLayout")
        
        # 采样频率
        self.freq_widget = QtWidgets.QWidget()
        self.freq_layout = QtWidgets.QHBoxLayout(self.freq_widget)
        self.freq_layout.setContentsMargins(0,0,0,0)
        self.freq_layout.setSpacing(5)
        self.freq_label = QtWidgets.QLabel(Dialog)
        self.freq_label.setObjectName("freq_label")
        self.freq_label.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.freq_layout.addWidget(self.freq_label)
        self.freq_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.freq_lineEdit.setObjectName("freq_lineEdit")
        self.freq_lineEdit.setMaximumWidth(80)
        self.freq_lineEdit.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.freq_layout.addWidget(self.freq_lineEdit)
        self.freq_unit_label = QtWidgets.QLabel(Dialog)
        self.freq_unit_label.setObjectName("freq_unit_label")
        self.freq_unit_label.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.freq_layout.addWidget(self.freq_unit_label)
        self.params_horizontalLayout.addWidget(self.freq_widget)
        
        # 监控时长
        self.duration_widget = QtWidgets.QWidget()
        self.duration_layout = QtWidgets.QHBoxLayout(self.duration_widget)
        self.duration_layout.setContentsMargins(0,0,0,0)
        self.duration_layout.setSpacing(5)
        self.duration_label = QtWidgets.QLabel(Dialog)
        self.duration_label.setObjectName("duration_label")
        self.duration_label.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.duration_layout.addWidget(self.duration_label)
        self.duration_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.duration_lineEdit.setObjectName("duration_lineEdit")
        self.duration_lineEdit.setMaximumWidth(80)
        self.duration_lineEdit.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.duration_layout.addWidget(self.duration_lineEdit)
        self.duration_comboBox = QtWidgets.QComboBox(Dialog)
        self.duration_comboBox.setObjectName("duration_comboBox")
        self.duration_comboBox.addItem("")
        self.duration_comboBox.addItem("")
        self.duration_comboBox.addItem("")
        self.duration_comboBox.addItem("")
        self.duration_comboBox.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.duration_layout.addWidget(self.duration_comboBox)
        self.params_horizontalLayout.addWidget(self.duration_widget)
        
        # 嵌入式
        self.embedded_widget = QtWidgets.QWidget()
        self.embedded_layout = QtWidgets.QHBoxLayout(self.embedded_widget)
        self.embedded_layout.setContentsMargins(0,0,0,0)
        self.embedded_layout.setSpacing(5)
        self.embedded_label = QtWidgets.QLabel(Dialog)
        self.embedded_label.setObjectName("embedded_label")
        self.embedded_label.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.embedded_layout.addWidget(self.embedded_label)
        self.embedded_checkBox = QtWidgets.QCheckBox(Dialog)
        self.embedded_checkBox.setText("")
        self.embedded_checkBox.setObjectName("embedded_checkBox")
        self.embedded_layout.addWidget(self.embedded_checkBox)
        self.params_horizontalLayout.addWidget(self.embedded_widget)
        
        # 加弹性空间让控件靠左
        spacer_params = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.params_horizontalLayout.addItem(spacer_params)
        
        self.verticalLayout.addLayout(self.params_horizontalLayout)
        
        # 状态栏
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout.setSpacing(100)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        
        # 连接状态一组（紧贴）
        self.ssh_status_layout_inner = QtWidgets.QHBoxLayout()
        self.ssh_status_layout_inner.setContentsMargins(0,0,0,0)
        self.ssh_status_layout_inner.setSpacing(5)
        self.ssh_label = QtWidgets.QLabel(Dialog)
        self.ssh_label.setObjectName("ssh_label")
        self.ssh_status_layout_inner.addWidget(self.ssh_label)
        self.ssh_stutas_label = QtWidgets.QLabel(Dialog)
        self.ssh_stutas_label.setText("")
        self.ssh_stutas_label.setObjectName("ssh_stutas_label")
        self.ssh_status_layout_inner.addWidget(self.ssh_stutas_label)
        self.horizontalLayout.addLayout(self.ssh_status_layout_inner)
        
        # 监控状态一组（紧贴）
        self.monitor_status_layout_inner = QtWidgets.QHBoxLayout()
        self.monitor_status_layout_inner.setContentsMargins(0,0,0,0)
        self.monitor_status_layout_inner.setSpacing(5)
        self.monitor_label = QtWidgets.QLabel(Dialog)
        self.monitor_label.setObjectName("monitor_label")
        self.monitor_status_layout_inner.addWidget(self.monitor_label)
        self.monitor_stutas_label = QtWidgets.QLabel(Dialog)
        self.monitor_stutas_label.setText("")
        self.monitor_stutas_label.setObjectName("monitor_stutas_label")
        self.monitor_status_layout_inner.addWidget(self.monitor_stutas_label)
        self.horizontalLayout.addLayout(self.monitor_status_layout_inner)
        
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        
        self.verticalLayout.addLayout(self.horizontalLayout)
        
        # 日志
        self.log_label = QtWidgets.QLabel(Dialog)
        self.log_label.setObjectName("log_label")
        self.verticalLayout.addWidget(self.log_label)
        self.log_textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.log_textBrowser.setObjectName("log_textBrowser")
        self.log_textBrowser.setMinimumHeight(200)
        self.log_textBrowser.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addWidget(self.log_textBrowser)
        
        # 按钮
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_pushButton = QtWidgets.QPushButton(Dialog)
        self.start_pushButton.setObjectName("start_pushButton")
        self.horizontalLayout_2.addWidget(self.start_pushButton)
        self.stop_pushButton = QtWidgets.QPushButton(Dialog)
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.horizontalLayout_2.addWidget(self.stop_pushButton)
        self.clean_pushButton = QtWidgets.QPushButton(Dialog)
        self.clean_pushButton.setObjectName("clean_pushButton")
        self.horizontalLayout_2.addWidget(self.clean_pushButton)
        self.download_pushButton = QtWidgets.QPushButton(Dialog)
        self.download_pushButton.setObjectName("download_pushButton")
        self.horizontalLayout_2.addWidget(self.download_pushButton)
        self.watch_pushButton = QtWidgets.QPushButton(Dialog)
        self.watch_pushButton.setObjectName("watch_pushButton")
        self.horizontalLayout_2.addWidget(self.watch_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "资源监控面板"))
        self.process_names_label.setText(_translate("Dialog", "进程名称"))
        self.process_input_plainTextEdit.setPlaceholderText(_translate("Dialog", "1.填写要监控的进程名称，多进程用/分割，例如hbfec/cetc\n2.模糊匹配：进程名包含关键词即可，无需完全一致\n3.windows进程无需末尾.exe\n4.不填写时只监控系统"))
        self.freq_label.setText(_translate("Dialog", "采样频率"))
        self.freq_unit_label.setText(_translate("Dialog", "秒"))
        self.duration_label.setText(_translate("Dialog", "监控时长(0=无限)"))
        self.duration_comboBox.setItemText(0, _translate("Dialog", "秒"))
        self.duration_comboBox.setItemText(1, _translate("Dialog", "分钟"))
        self.duration_comboBox.setItemText(2, _translate("Dialog", "小时"))
        self.duration_comboBox.setItemText(3, _translate("Dialog", "天"))
        self.process_label.setText(_translate("Dialog", "进程监控内容"))
        self.sys_plainTextEdit.setPlainText(_translate("Dialog", "已用内存(MB)     CPU使用率(%)\n磁盘读(KB/s)     磁盘写(KB/s)\n系统文件描述符   系统Socket描述符  进程数\n"))
        self.sys_label.setText(_translate("Dialog", "系统监控内容"))
        self.process_plainTextEdit.setPlainText(_translate("Dialog", "已用内存(MB)    CPU使用率(%)\n文件描述符      Socket描述符"))
        self.embedded_label.setText(_translate("Dialog", "嵌入式系统(ash)"))
        self.ssh_label.setText(_translate("Dialog", "连接状态："))
        self.monitor_label.setText(_translate("Dialog", "监控状态："))
        self.log_label.setText(_translate("Dialog", "监控日志："))
        self.start_pushButton.setText(_translate("Dialog", "开始监控"))
        self.stop_pushButton.setText(_translate("Dialog", "停止监控"))
        self.clean_pushButton.setText(_translate("Dialog", "清除数据"))
        self.download_pushButton.setText(_translate("Dialog", "下载数据"))
        self.watch_pushButton.setText(_translate("Dialog", "监控绘图"))
